development:
  adapter: postgresql
  database: railsgirls_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: railsgirls_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: railsgirls_production
  pool: 5
  timeout: 5000